```properties
server.port=5000
spring.application.name=api-gateway

# Ruta del servicio de productos
spring.cloud.gateway.server.webflux.routes[0].id=productos-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PRODUCTOS-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/productos,/api/productos/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=AddRequestHeader=X-Gateway-Passed,true

# Ruta del servicio de usuarios
spring.cloud.gateway.server.webflux.routes[1].id=usuarios-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USUARIOS-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/usuarios,/api/usuarios/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=AddRequestHeader=X-Gateway-Passed,true

# Configuración de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
```